"""add task query index

Revision ID: 1717a33f6230
Revises: 956c550fda58
Create Date: 2026-09-19 06:53:55.725310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1717a33f6230'
down_revision: Union[str, Sequence[str], None] = '956c550fda58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_tasks_user_id_created_at', 'user_tasks', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_tasks_user_id_created_at', table_name='user_tasks')
    # ### end Alembic commands ###
