"""add task metadata

Revision ID: 956c550fda58
Revises: 036b8a10321d
Create Date: 2026-09-18 14:59:13.922882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956c550fda58'
down_revision: Union[str, Sequence[str], None] = '036b8a10321d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "user_tasks",
        sa.Column(
            "priority",
            sa.String(),
            nullable=False,
            server_default="medium",
        ),
    )

    op.add_column(
        "user_tasks",
        sa.Column(
            "due_date",
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.add_column(
        "user_tasks",
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    op.add_column(
        "user_tasks",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    op.alter_column(
        "user_tasks",
        "title",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )

    op.alter_column(
        "user_tasks",
        "description",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )

    op.alter_column(
        "user_tasks",
        "is_completed",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )

    op.alter_column(
        "user_tasks",
        "user_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_tasks', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_tasks', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_tasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user_tasks', 'updated_at')
    op.drop_column('user_tasks', 'created_at')
    op.drop_column('user_tasks', 'due_date')
    op.drop_column('user_tasks', 'priority')
    # ### end Alembic commands ###
